#!/usr/bin/env bash
set -euo pipefail

echo "${0##*/}": Building...
dotnet build src/ --configuration Release --nologo

echo "${0##*/}": Testing...
dotnet test src/ --configuration Release --no-build --nologo "${1:-}" "${2:-}"
